In [47]:
print("hello")

hello


In [48]:
print( 1,2,3,4,5)

1 2 3 4 5


In [49]:
print({1,2,3,4})

{1, 2, 3, 4}


In [50]:
print("hello","world")

hello world


In [51]:
print(["hello","world"])

['hello', 'world']


In [52]:
type(val)

dict

In [53]:
val = {"key": "value"}
val

{'key': 'value'}

In [54]:
type(val)

dict

In [55]:
tup = {(1,2),(3,4)}
tup

{(1, 2), (3, 4)}

In [56]:
type(tup)

set

In [57]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [58]:
a.insert(2,6)

In [59]:
a

[1, 2, 6, 3, 4, 5]

In [60]:
a.remove(2)

In [61]:
a

[1, 6, 3, 4, 5]

In [62]:
for i in a :
    print(i)

1
6
3
4
5


In [63]:
print(a+a)

[1, 6, 3, 4, 5, 1, 6, 3, 4, 5]


In [64]:
c=[[1,2],[3,4]]
c

[[1, 2], [3, 4]]

In [75]:
import numpy as np
d = np.array(c)
d

array([[1, 2],
       [3, 4]])

numpy.ndarray

In [78]:
e=np.array([[6,7],[8,9]])
e

array([[6, 7],
       [8, 9]])

In [79]:
d+e

array([[ 7,  9],
       [11, 13]])

In [80]:
d*e

array([[ 6, 14],
       [24, 36]])

In [87]:
f = np.dot(d,e)
f

array([[22, 25],
       [50, 57]])

In [84]:
np.random.randint(0,100,6)

array([54, 28, 55, 33, 20, 46])

In [85]:
np.random.randint(0,100,6).reshape(2,3)


array([[93, 70, 33],
       [53, 82, 28]])

In [86]:
import pandas as pd

In [98]:
df = pd.DataFrame((["ABC","1___01"],["XYZ","1___02"]),index=["1","2"],columns=["NAME","USN"])
df                                                                               

NAME     USN
1  ABC  1___01
2  XYZ  1___02

In [99]:
df = pd.DataFrame((["ABC","1___01"],["XYZ","1___02"],["PQR","1___03"]),index=["1","2","3"],columns=["NAME","USN"])
df                                                                               

NAME     USN
1  ABC  1___01
2  XYZ  1___02
3  PQR  1___03

In [102]:
df = pd.DataFrame((["ABC","1___01","7856876"],["XYZ","1___02","56478567"],["PQR","1___03","6578967"]),index=["1","2","3"],columns=["NAME","USN","PHONE NO"])
df                                                                               df

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [103]:
df.loc["1"]

NAME            ABC
USN          1___01
PHONE NO    7856876
Name: 1, dtype: object

In [104]:
df.loc["2"]

NAME             XYZ
USN           1___02
PHONE NO    56478567
Name: 2, dtype: object

In [105]:
df.loc["3"]

NAME            PQR
USN          1___03
PHONE NO    6578967
Name: 3, dtype: object

In [106]:
type(df.loc["1"])

pandas.core.series.Series

In [107]:
type(df)

pandas.core.frame.DataFrame

In [108]:
df.iloc[:,:]

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [109]:
df.iloc[:-1]

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567

In [110]:
df.iloc[:,-1]

1     7856876
2    56478567
3     6578967
Name: PHONE NO, dtype: object

In [115]:
df.iloc[:,0]

1    ABC
2    XYZ
3    PQR
Name: NAME, dtype: object

In [122]:
df.iloc[:,0]

1    ABC
2    XYZ
3    PQR
Name: NAME, dtype: object

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   NAME      3 non-null      object
 1   USN       3 non-null      object
 2   PHONE NO  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes


In [124]:
df.describe()

NAME     USN PHONE NO
count     3       3        3
unique    3       3        3
top     ABC  1___01  7856876
freq      1       1        1

In [126]:
df.head(3)

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [130]:
df1=df.dropna(axis=0)
df1

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [131]:
df1

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [132]:
df

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [135]:
df.fillna("full")

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [138]:
df=df.fillna("1___01")

In [141]:
df.to_csv("/tmp/a.csv")

In [142]:
cat /tmp/a.csv

,NAME,USN,PHONE NO
1,ABC,1___01,7856876
2,XYZ,1___02,56478567
3,PQR,1___03,6578967


In [144]:
df2 = pd.read_csv("/tmp/a.csv")
df2

Unnamed: 0 NAME     USN  PHONE NO
0           1  ABC  1___01   7856876
1           2  XYZ  1___02  56478567
2           3  PQR  1___03   6578967

In [147]:
data = {"A":"B","C":"D"}
data

{'A': 'B', 'C': 'D'}

In [148]:
type(data)

dict

In [153]:
data.to_json("/tmp/c.json")

AttributeError: 'dict' object has no attribute 'to_json'

In [160]:
df.to_json("/tmp/a.json")

In [161]:
data1 = pd.read_json("/tmp/a.json")
data1

NAME     USN  PHONE NO
1  ABC  1___01   7856876
2  XYZ  1___02  56478567
3  PQR  1___03   6578967

In [166]:
import matplotlib as plt
 %matplotlib.inline


IndentationError: unexpected indent (802904532.py, line 2)

In [167]:
import matploblib as pl


ModuleNotFoundError: No module named 'matploblib'

In [171]:
import matplotlib as plt
import numpy as np
%matplotlib inline


In [175]:
x = np.arange(0,10)
y = np.arange(11,21)

In [173]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [177]:
plt.plot(x,y)

AttributeError: module 'matplotlib' has no attribute 'plot'